version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nisa-profile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nisa_profile
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nisa-profile:
    container_name: nisa-profile
    image: registry.gigsnow.in/nisa-profile:1.0.2
    build: .
    ports:
      - "5175:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nisa_profile
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
